// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/granitebps/fiber-api/pkg/core"
	"github.com/granitebps/fiber-api/src/handler"
)

// Injectors from wire.go:

func SetupDependencies(c *core.Core) *handler.Handler {
	handlerHandler := handler.NewHandler(c)
	return handlerHandler
}
